---
title: "Data Cleaning and Analysis"
author: "Miles D. Williams"
date: "December 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

In this file, I load and clean raw AidData data on Chinese financial flows to create a data file for analysis. I merge this with data from the Cline Center's Archer portal on Xinhwua coverage of developing countries.

```{r libraries}
try(library(tidyverse))
library(tidytext)
library(foreach)
```

```{r}
# Get aid data
read_csv("china_aid_data.csv") %>% 
  filter(recommended_for_research == T) %>%
  rename(country= recipient_condensed) %>%
  group_by(country, year) %>%
  summarize(aid = sum(usd_defl_2014)) -> china_aid

# Controls
pwt8::pwt8.1 -> penn
penn %>%
  select(country, year, rgdpna, pop, emp) %>%
  right_join(china_aid) -> china_aid

#library(devtools)
#install_github("ropengov/rqog")
library(rqog)
read_qog(which_data="basic", data_type = "time-series") -> basic_qog
basic_qog %>%
  rename(country = cname) %>%
  select(country, year, icrg_qog, vdem_polyarchy) %>%
  right_join(china_aid) -> china_aid

china_aid %>%
  mutate(
    rgdpna = rgdpna/pop,
    emp = emp/pop
  ) -> china_aid
```


```{r}
# Get Xinhua data
read_tsv("12_11_2019 20_17_02.tsv") %>%
  filter(publisher == "Xinhua General News Service") -> xinhua

# Make year variable
xinhua %>%
  mutate(year = str_extract(publication_date, pattern = "[0-9][0-9] ")) %>%
  mutate(year = paste0("20",year) %>% as.numeric) -> xinhua
```


```{r}
foreach(
  i = unique(china_aid$country),  
  .combine = 'rbind'
) %do% {
  foreach(j = unique(china_aid$year), 
          .combine = 'rbind') %do% {
  xinhua %>%
    filter(year == j) %>%
    unnest_tokens(country_names, country) %>%
    .$country_names -> patterns
  china_aid %>%
    filter(country == i, year == j) -> country_year
  str_detect(
      tolower(country_year$country),
      pattern = unique(patterns)
    ) %>%
    sum(., na.rm=T) -> counts
  tibble(
    country = i,
    year = j,
    counts = counts
  )
        }
} -> count_data
```

```{r}
china_aid %>%
  left_join(count_data, by = c("year","country")) %>%
  group_by(year) %>%
  mutate(aid_rank = rank(aid)) -> analysis_data
ggplot(data = analysis_data) +
  aes(log(aid_rank), as.numeric(counts>0)) +
  geom_jitter(width = .05, height = .05, alpha = .5) +
  geom_smooth(method = "lm")
```



```{r}
library(lmtest)
library(sandwich)
lm(log(aid_rank) ~ I(counts>0) + as.factor(year), analysis_data) -> model1
lm(counts>0 ~ log(aid_rank) + as.factor(year), analysis_data) -> model2

model1 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "I(counts > 0)TRUE") %>%
  mutate(term = "Coverage") %>%
  dotwhisker::dwplot(dot_args = list(color = "black")) +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Rank (ln)"
  ) +
  theme(
    axis.title.x = element_text(face = "italic")
  ) -> p1
model2 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank)") %>%
  mutate(term = "Rank (ln)") %>%
  dotwhisker::dwplot(dot_args = list(color = "black")) +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Pr(Coverage)"
  ) +
  theme(
    axis.title.x = element_text(face = "italic")
  ) -> p2
gridExtra::grid.arrange(p1, p2, ncol = 2, 
                        top = grid::textGrob(
                          "Contemporaneous coverage and aid allocation",
                          gp = grid::gpar(fontface = 4, fontsize = 14),
                          hjust = .5
                        )) -> plot_1
ggsave(plot_1, filename = "plot_1.png", 
       units = "in", height = 3, width = 8)
```

```{r}
analysis_data %>%
  group_by(country) %>%
  mutate(count_lag = lag(counts, order_by = year),
         aid_rank_lag = lag(aid_rank, order_by = year)) %>%
  ungroup() -> analysis_data

lm(log(aid_rank) ~ I(count_lag>0), analysis_data) -> model3
lm(counts>0 ~ log(aid_rank_lag), analysis_data) -> model4

lm(log(aid_rank) ~ I(count_lag>0) + as.factor(year), analysis_data) -> model5
lm(counts>0 ~ log(aid_rank_lag) + as.factor(year), analysis_data) -> model6

lm(log(aid_rank) ~ I(count_lag>0) + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy, analysis_data) -> model7
lm(counts>0 ~ log(aid_rank_lag) + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy, analysis_data) -> model8

lm(log(aid_rank) ~ I(count_lag>0) + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy + 
     as.factor(year), analysis_data) -> model9
lm(counts>0 ~ log(aid_rank_lag) + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy + 
     as.factor(year), analysis_data) -> model10

rbind(model3 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "I(count_lag > 0)TRUE") %>%
  mutate(term = "Coverage\n(prior year)", model = "FE: no; Controls: no"),
  model5 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "I(count_lag > 0)TRUE") %>%
  mutate(term = "Coverage\n(prior year)", model = "FE: yes; Controls: no"),
  model7 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "I(count_lag > 0)TRUE") %>%
  mutate(term = "Coverage\n(prior year)", model = "FE: no; Controls: yes"),
  model9 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "I(count_lag > 0)TRUE") %>%
  mutate(term = "Coverage\n(prior year)", model = "FE: yes; Controls: yes")) %>%
  dotwhisker::dwplot() +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Rank (ln)"
  ) +
  theme(
    axis.title.x = element_text(face = "italic"),
    legend.position = c(.25,.2),
    legend.title = element_blank(),
    legend.text = element_text(size = 5)
  ) -> p3
rbind(model4 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: no; Controls: no"),
  model6 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: yes; Controls: no"),
  model8 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: no; Controls: yes"),
  model10 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: yes; Controls: yes")) %>%
  dotwhisker::dwplot() +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Pr(Coverage)"
  ) +
  theme(
    axis.title.x = element_text(face = "italic"),
    legend.position = "none"
  ) -> p4
gridExtra::grid.arrange(p3, p4, ncol = 2, 
                        top = grid::textGrob(
                          "Estimates with lagged predictors",
                          gp = grid::gpar(fontface = 4, fontsize = 14),
                          hjust = .5
                        )) -> plot_2
ggsave(plot_2, filename = "plot_2.png",
       units = "in", height = 4, width = 8)
```


```{r}
library(stargazer)
```

```{r}
list(
    sqrt(diag(vcovHC(model3, "HC2"))),
    sqrt(diag(vcovHC(model4, "HC2"))),
    sqrt(diag(vcovHC(model5, "HC2"))),
    sqrt(diag(vcovHC(model6, "HC2"))),
    sqrt(diag(vcovHC(model7, "HC2"))),
    sqrt(diag(vcovHC(model8, "HC2"))),
    sqrt(diag(vcovHC(model9, "HC2"))),
    sqrt(diag(vcovHC(model10, "HC2")))
  ) -> ses
```

```{r}
stargazer(
  header = F,
  title = "OLS Coefficients for Chinese Aid and Xinhua Coverage of Recipients",
  model3, model4, model5, model6, model7, model8, model9, model10,
  se = ses,
  dep.var.caption = "Outcome Variable",
  dep.var.labels = rep(c("Rank Aid (ln)", "Pr(Coverage)"), len = 8),
  column.sep.width = "0pt",
  keep = c(1:3, 16:20),
  covariate.labels = c(
    "Coverage lagged",
    "Rank Aid lagged (ln)",
    "*Controls*",
    "Employment Rate (ln)",
    "Population (ln)",
    "Income (ln)",
    "V-Dem"
  ),
  add.lines = list(
    c("Year FE", "No", "No", "Yes", "Yes", "No", "No", "Yes", "Yes")
  ),
  out = "reg_table1.tex"
) 
```

```{r}
xinhua %>%
  unnest_tokens(country_name, country) %>%
  group_by(country_name, year) %>%
  summarize_if(is.numeric, mean) %>%
  arrange(-mf_moralitygeneral) %>%
  select(country_name, year, mf_moralitygeneral) %>%
  rename(country = country_name) -> morality
analysis_data %>%
  mutate(country = tolower(country)) %>%
  left_join(morality, by = c("country","year")) -> analysis_data
ggplot(data = analysis_data) +
  aes(log(aid_rank), log(mf_moralitygeneral + 1)) +
  geom_point() +
  geom_smooth(method = "lm")
```


```{r}
lm(log(aid_rank) ~ mf_moralitygeneral + as.factor(year), analysis_data) -> model1
lm(mf_moralitygeneral ~ log(aid_rank) + as.factor(year), analysis_data) -> model2

model1 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "mf_moralitygeneral") %>%
  mutate(term = "Coverage Sentiment") %>%
  dotwhisker::dwplot(dot_args = list(color = "black")) +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Rank (ln)"
  ) +
  theme(
    axis.title.x = element_text(face = "italic")
  ) -> p1
model2 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank)") %>%
  mutate(term = "Rank (ln)") %>%
  dotwhisker::dwplot(dot_args = list(color = "black")) +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Virtuous Sentiment"
  ) +
  theme(
    axis.title.x = element_text(face = "italic")
  ) -> p2
gridExtra::grid.arrange(p1, p2, ncol = 2, 
                        top = grid::textGrob(
                          "Contemporaneous sentiment of coverage and aid allocation",
                          gp = grid::gpar(fontface = 4, fontsize = 14),
                          hjust = .5
                        )) -> plot_3
ggsave(plot_3, filename = "plot_3.png", 
       units = "in", height = 3, width = 8)
```

```{r}
analysis_data %>%
  group_by(country) %>%
  mutate(sent_lag = lag(mf_moralitygeneral, order_by = year)) %>%
  ungroup() -> analysis_data

lm(log(aid_rank) ~ sent_lag, analysis_data) -> model3
lm(sent_lag ~ log(aid_rank_lag), analysis_data) -> model4

lm(log(aid_rank) ~ sent_lag + as.factor(year), analysis_data) -> model5
lm(sent_lag ~ log(aid_rank_lag) + as.factor(year), analysis_data) -> model6

lm(log(aid_rank) ~ sent_lag + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy, analysis_data) -> model7
lm(sent_lag ~ log(aid_rank_lag) + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy, analysis_data) -> model8

lm(log(aid_rank) ~ sent_lag + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy + 
     as.factor(year), analysis_data) -> model9
lm(sent_lag ~ log(aid_rank_lag) + log(emp) + log(pop) + log(rgdpna) + vdem_polyarchy + 
     as.factor(year), analysis_data) -> model10

rbind(model3 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "sent_lag") %>%
  mutate(term = "Virtue\n(prior year)", model = "FE: no; Controls: no"),
  model5 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "sent_lag") %>%
  mutate(term = "Virtue\n(prior year)", model = "FE: yes; Controls: no"),
  model7 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "sent_lag") %>%
  mutate(term = "Virtue\n(prior year)", model = "FE: no; Controls: yes"),
  model9 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "sent_lag") %>%
  mutate(term = "Virtue\n(prior year)", model = "FE: yes; Controls: yes")) %>%
  dotwhisker::dwplot() +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Rank (ln)"
  ) +
  theme(
    axis.title.x = element_text(face = "italic"),
    legend.position = c(.25,.175),
    legend.title = element_blank(),
    legend.text = element_text(size = 5)
  ) -> p3
rbind(model4 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: no; Controls: no"),
  model6 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: yes; Controls: no"),
  model8 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: no; Controls: yes"),
  model10 %>%
  coeftest(., vcov = vcovHC(., "HC2")) %>%
  broom::tidy(.) %>%
  filter(term == "log(aid_rank_lag)") %>%
  mutate(term = "Rank (ln)\n(prior year)", model = "FE: yes; Controls: yes")) %>%
  dotwhisker::dwplot() +
  geom_vline(xintercept = 0) +
  labs(
    x = "Estimated Increase in Virtuous Sentiment"
  ) +
  theme(
    axis.title.x = element_text(face = "italic"),
    legend.position = "none"
  ) -> p4
gridExtra::grid.arrange(p3, p4, ncol = 2, 
                        top = grid::textGrob(
                          "Estimates with lagged predictors",
                          gp = grid::gpar(fontface = 4, fontsize = 14),
                          hjust = .5
                        )) -> plot_4
ggsave(plot_4, filename = "plot_4.png",
       units = "in", height = 4, width = 8)
```


```{r}
list(
    sqrt(diag(vcovHC(model3, "HC2"))),
    sqrt(diag(vcovHC(model4, "HC2"))),
    sqrt(diag(vcovHC(model5, "HC2"))),
    sqrt(diag(vcovHC(model6, "HC2"))),
    sqrt(diag(vcovHC(model7, "HC2"))),
    sqrt(diag(vcovHC(model8, "HC2"))),
    sqrt(diag(vcovHC(model9, "HC2"))),
    sqrt(diag(vcovHC(model10, "HC2")))
  ) -> ses
```

```{r}
stargazer(
  header = F,
  title = "OLS Coefficients for Chinese Aid and Sentiment of Xinhua Coverage of Recipients",
  model3, model4, model5, model6, model7, model8, model9, model10,
  se = ses,
  dep.var.caption = "Outcome Variable",
  dep.var.labels = rep(c("Rank Aid (ln)", "Pr(Coverage)"), len = 8),
  column.sep.width = "0pt",
  keep = c(1:3, 16:20),
  covariate.labels = c(
    "Virtuous Sentiment lagged",
    "Rank Aid lagged (ln)",
    "*Controls*",
    "Employment Rate (ln)",
    "Population (ln)",
    "Income (ln)",
    "V-Dem"
  ),
  add.lines = list(
    c("Year FE", "No", "No", "Yes", "Yes", "No", "No", "Yes", "Yes")
  ),
  out = "reg_table2.tex"
) 
```